package rewriter

import (
	"strings"
	"testing"
)

func TestRewriteInteriorFunction(t *testing.T) {
	src := `package main

func ProcessOrder(ctx context.Context, order Order) error {
	return nil
}
`
	r := New("myrepo", NewPatternMatcher(nil))
	result, err := r.RewriteSource("orders.go", []byte(src))
	if err != nil {
		t.Fatal(err)
	}

	out := string(result)
	if !strings.Contains(out, `tracert.Enter("myrepo/main.ProcessOrder")`) {
		t.Errorf("should inject Enter call, got:\n%s", out)
	}
	if !strings.Contains(out, "tracert.Exit(") {
		t.Error("should inject defer Exit call")
	}
	if !strings.Contains(out, "tracert.ExitPanic(") {
		t.Error("should inject panic recovery with ExitPanic")
	}
	if !strings.Contains(out, "recover()") {
		t.Error("should have recover() in defer")
	}
}

func TestRewriteBoundaryFunction(t *testing.T) {
	src := `package handlers

func (h *OrderHandler) Create(w http.ResponseWriter, r *http.Request) {
	return
}
`
	patterns := []string{"*.Create"}
	r := New("myrepo", NewPatternMatcher(patterns))
	result, err := r.RewriteSource("handlers.go", []byte(src))
	if err != nil {
		t.Fatal(err)
	}

	out := string(result)
	// Boundary function should pass args to Enter
	if !strings.Contains(out, `tracert.Enter("myrepo/handlers.OrderHandler.Create", w, r)`) {
		t.Errorf("should inject Enter with args for boundary func, got:\n%s", out)
	}
}

func TestRewriteGoStatement(t *testing.T) {
	src := `package main

func Start() {
	go processAsync(item)
}
`
	r := New("myrepo", NewPatternMatcher(nil))
	result, err := r.RewriteSource("start.go", []byte(src))
	if err != nil {
		t.Fatal(err)
	}

	out := string(result)
	if !strings.Contains(out, "tracert.Go(func()") {
		t.Errorf("should rewrite go statement, got:\n%s", out)
	}
	// CRITICAL: Verify the `go` keyword is removed
	if strings.Contains(out, "go tracert.Go(") {
		t.Errorf("should NOT have 'go' keyword before tracert.Go, got:\n%s", out)
	}
}

func TestRewriteAnonymousGoroutine(t *testing.T) {
	src := `package main

func Start() {
	go func() {
		doWork()
	}()
}
`
	r := New("myrepo", NewPatternMatcher(nil))
	result, err := r.RewriteSource("start.go", []byte(src))
	if err != nil {
		t.Fatal(err)
	}

	out := string(result)
	if !strings.Contains(out, "tracert.Go(func()") {
		t.Errorf("should rewrite anonymous goroutine, got:\n%s", out)
	}
	if strings.Contains(out, "go tracert.Go(") {
		t.Errorf("should NOT have 'go' keyword, got:\n%s", out)
	}
}

func TestSkipGeneratedFiles(t *testing.T) {
	src := `// Code generated by protoc. DO NOT EDIT.
package pb

func GeneratedFunc() {}
`
	r := New("myrepo", NewPatternMatcher(nil))
	result, err := r.RewriteSource("gen.go", []byte(src))
	if err != nil {
		t.Fatal(err)
	}

	out := string(result)
	if strings.Contains(out, "tracert.Enter") {
		t.Error("should not instrument generated files")
	}
}

func TestRewriteMethodWithReceiver(t *testing.T) {
	src := `package auth

type Service struct{}

func (s *Service) Authenticate(token string) (User, error) {
	return User{}, nil
}
`
	r := New("myrepo", NewPatternMatcher(nil))
	result, err := r.RewriteSource("auth.go", []byte(src))
	if err != nil {
		t.Fatal(err)
	}

	out := string(result)
	if !strings.Contains(out, `tracert.Enter("myrepo/auth.Service.Authenticate")`) {
		t.Errorf("should use Receiver.Method format, got:\n%s", out)
	}
}
